[workspace]
resolver = "2"
members = [
    "contracts/wallet",
    "contracts/factory",
    "contracts/policy",
]

[workspace.dependencies]
soroban-sdk = "27.0.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "debuginfo"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
